# Generated by Django 6.0.3 on 2026-03-20 11:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import models_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morceau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('afrobeat', 'Afrobeat'), ('trap', 'Trap'), ('rnb', 'RnB'), ('gospel', 'Gospel'), ('coupe-decale', 'Coupé-Décalé'), ('hiphop', 'Hip-Hop'), ('pop', 'Pop'), ('autre', 'Autre')], max_length=30)),
                ('pochette', models.ImageField(upload_to='morceaux/pochettes/', validators=[models_app.models.valider_image])),
                ('fichier_mp3', models.FileField(upload_to='morceaux/audio/', validators=[models_app.models.valider_audio])),
                ('duree', models.PositiveIntegerField(default=0, help_text='Durée en secondes')),
                ('points', models.PositiveIntegerField(default=0)),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_sortie', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'morceaux',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonceur', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='publicites/', validators=[models_app.models.valider_image])),
                ('video', models.FileField(blank=True, null=True, upload_to='publicites/videos/', validators=[models_app.models.valider_video])),
                ('url_cible', models.URLField(blank=True, help_text='URL de redirection au clic sur la pub')),
                ('duree_secondes', models.PositiveSmallIntegerField(default=7, help_text='Secondes à attendre avant de télécharger')),
                ('actif', models.BooleanField(default=True)),
                ('nb_affichages', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'publicites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('utilisateur', 'Utilisateur'), ('artiste', 'Artiste'), ('administrateur', 'Administrateur')], default='utilisateur', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=models_app.models.chemin_avatar, validators=[models_app.models.valider_image])),
                ('pays', models.CharField(blank=True, max_length=60)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfilAdministrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('super', 'Super Administrateur'), ('standard', 'Administrateur Standard')], default='standard', max_length=10)),
                ('service', models.CharField(blank=True, help_text='Service ou département', max_length=100)),
                ('cree_par', models.ForeignKey(blank=True, help_text='Admin qui a créé ce compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_crees', to='models_app.profiladministrateur')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profils_administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('or', 'Or'), ('platine', 'Platine'), ('diamant', 'Diamant')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('morceau', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='models_app.morceau')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models_app.profiladministrateur')),
            ],
            options={
                'db_table': 'certifications',
            },
        ),
        migrations.CreateModel(
            name='ProfilArtiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_artiste', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artistes/photos/', validators=[models_app.models.valider_image])),
                ('photo_cover', models.ImageField(blank=True, null=True, upload_to='artistes/covers/', validators=[models_app.models.valider_image])),
                ('genre', models.CharField(blank=True, choices=[('afrobeat', 'Afrobeat'), ('trap', 'Trap'), ('rnb', 'RnB'), ('gospel', 'Gospel'), ('coupe-decale', 'Coupé-Décalé'), ('hiphop', 'Hip-Hop'), ('pop', 'Pop'), ('autre', 'Autre')], max_length=50)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False, help_text='Vérifié par un administrateur')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_artiste', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profils_artistes',
                'ordering': ['nom_artiste'],
            },
        ),
        migrations.AddField(
            model_name='morceau',
            name='artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morceaux', to='models_app.profilartiste'),
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_courte', models.CharField(blank=True, max_length=160)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profils_utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Telechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('pub_vue', models.BooleanField(default=False, help_text="Publicité regardée jusqu'au bout")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('morceau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_app.morceau')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telechargements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier_video', models.FileField(blank=True, null=True, upload_to='morceaux/videos/', validators=[models_app.models.valider_video])),
                ('youtube_url', models.URLField(blank=True, help_text='Lien YouTube si pas de fichier local')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='morceaux/thumbnails/', validators=[models_app.models.valider_image])),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='models_app.profilartiste')),
                ('morceau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='models_app.morceau')),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('morceau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_app.morceau')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'votes',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('morceau', 'user'), name='un_vote_par_user_par_morceau')],
            },
        ),
        migrations.CreateModel(
            name='VueVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_app.video')),
            ],
            options={
                'db_table': 'vues_video',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('video', 'session_id'), name='une_vue_par_session_par_video')],
            },
        ),
    ]
