# Generated by Django 6.0.2 on 2026-03-20 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_commentairevideo_likevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to='models_app.profilartiste')),
            ],
            options={
                'db_table': 'abonnements',
                'constraints': [models.UniqueConstraint(fields=('abonne', 'artiste'), name='un_abonnement_par_user_par_artiste')],
            },
        ),
    ]
