# Generated by Django 6.0.2 on 2026-03-20 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_abonnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('vote', '👍 Vote sur ton morceau'), ('telechargement', '⬇ Téléchargement de ton morceau'), ('commentaire', '💬 Commentaire sur ta vidéo'), ('like', '❤ Like sur ta vidéo'), ('abonnement', '🔔 Nouvel abonné'), ('validation', '✅ Morceau validé par un admin'), ('refus', '❌ Morceau refusé par un admin')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('lien', models.CharField(blank=True, max_length=255)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
