# Generated by Django 6.0.2 on 2026-03-20 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcouteMorceau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('duree', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('morceau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecoutes', to='models_app.morceau')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecoutes_morceaux',
                'ordering': ['-created_at'],
            },
        ),
    ]
