# Generated by Django 6.0.2 on 2026-03-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_ecoutemorceau'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la vidéo'),
        ),
    ]
