# Generated by Django 6.0.2 on 2026-03-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceau',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='valide', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='valide', max_length=20),
        ),
    ]
